FROM {{.Base}}

LABEL org.opencontainers.image.source="{{.SourceURL}}" \
      org.opencontainers.image.title="{{.Title}}"{{if .Description}} \
      org.opencontainers.image.description="{{.Description}}"{{end}}

ARG TARGETARCH
ENV ARCH=$TARGETARCH

{{template "zypper.tmpl" .Packages}}

{{range .Tools}}# {{.Name}} {{.Version}}
{{.Install.Render}}

{{end}}{{if .HasGoInstall}}# Cleanup Go caches
RUN go clean -cache -modcache

{{end}}# We trust our base image and the repos that are pulled in workflows. Otherwise
# each workflow that uses our base images would have to add the step below.
RUN if (which git &> /dev/null); then \
        echo "Configuring system git safe directory"; \
        git config --system --add safe.directory '*'; \
    fi

ENTRYPOINT ["/bin/bash"]
