FROM registry.suse.com/bci/golang:1.26.2@sha256:0c1bfe51ea14f3e28b4730c725687331ce6aa24c61acea3b9735286789c873b9

LABEL org.opencontainers.image.source="https://github.com/rancher/ci-image" \
      org.opencontainers.image.title="Rancher go1.26 CI image" \
      org.opencontainers.image.description="CI image with Go 1.26 toolchain"

ARG TARGETARCH
ENV ARCH=$TARGETARCH

RUN zypper -n refresh && \
    zypper -n install \
        docker \
        gawk \
        git-core \
        jq \
        make \
        unzip \
        wget \
        skopeo \
    && \
    zypper -n clean -a && \
    rm -rf /var/log/{lastlog,tallylog,zypper.log,zypp/history,YaST2}

# cosign v3.0.6
RUN case "${ARCH}" in \
        amd64) CHECKSUM="c956e5dfcac53d52bcf058360d579472f0c1d2d9b69f55209e256fe7783f4c74" ;; \
        arm64) CHECKSUM="bedac92e8c3729864e13d4a17048007cfafa79d5deca993a43a90ffe018ef2b8" ;; \
        *) echo "Unsupported: ${ARCH}"; exit 1 ;; \
    esac && \
    export TMP_DIR=$(mktemp -d) && \
    case "${ARCH}" in \
        amd64) DOWNLOAD_URL="https://github.com/sigstore/cosign/releases/download/v3.0.6/cosign-linux-amd64" ;; \
        arm64) DOWNLOAD_URL="https://github.com/sigstore/cosign/releases/download/v3.0.6/cosign-linux-arm64" ;; \
    esac && \
    curl -fsSL --retry 3 --retry-delay 5 --retry-all-errors "${DOWNLOAD_URL}" > "${TMP_DIR}/cosign" && \
    printf "%s  %s\n" "${CHECKSUM}" "${TMP_DIR}/cosign" > "${TMP_DIR}/checksum.sha256" && \
    sha256sum -c "${TMP_DIR}/checksum.sha256" && \
    install "${TMP_DIR}/cosign" "/usr/local/bin/cosign" && \
    rm -rf "${TMP_DIR}"

# gh v2.89.0
RUN case "${ARCH}" in \
        amd64) CHECKSUM="d0422caade520530e76c1c558da47daebaa8e1203d6b7ff10ad7d6faba3490d8" ;; \
        arm64) CHECKSUM="9e64a623dfc242990aa5d9b3f507111149c4282f66b68eaad1dc79eeb13b9ce5" ;; \
        *) echo "Unsupported: ${ARCH}"; exit 1 ;; \
    esac && \
    export TMP_DIR=$(mktemp -d) && \
    export TMP_FILE="${TMP_DIR}/gh.tar.gz" && \
    case "${ARCH}" in \
        amd64) DOWNLOAD_URL="https://github.com/cli/cli/releases/download/v2.89.0/gh_2.89.0_linux_amd64.tar.gz"; EXTRACT="gh_2.89.0_linux_amd64/bin/gh" ;; \
        arm64) DOWNLOAD_URL="https://github.com/cli/cli/releases/download/v2.89.0/gh_2.89.0_linux_arm64.tar.gz"; EXTRACT="gh_2.89.0_linux_arm64/bin/gh" ;; \
    esac && \
    curl -fsSL --retry 3 --retry-delay 5 --retry-all-errors "${DOWNLOAD_URL}" > "${TMP_FILE}" && \
    printf "%s  %s\n" "${CHECKSUM}" "${TMP_FILE}" > "${TMP_DIR}/checksum.sha256" && \
    sha256sum -c "${TMP_DIR}/checksum.sha256" && \
    tar xzf "${TMP_FILE}" -C "${TMP_DIR}" && \
    install "${TMP_DIR}/${EXTRACT}" "/usr/local/bin/gh" && \
    rm -rf "${TMP_DIR}"

# helm v3.20.2
RUN case "${ARCH}" in \
        amd64) CHECKSUM="258e830a9e613c8a7a302d6059b4bb3b9758f2f3e1bb8ea0d707ce10a9a72fea" ;; \
        arm64) CHECKSUM="5ea2d6bc2cda3f8edf985e028809f5a9278f404fb8ab24044de9b7cb9b79a691" ;; \
        *) echo "Unsupported: ${ARCH}"; exit 1 ;; \
    esac && \
    export TMP_DIR=$(mktemp -d) && \
    export TMP_FILE="${TMP_DIR}/helm.tar.gz" && \
    case "${ARCH}" in \
        amd64) DOWNLOAD_URL="https://get.helm.sh/helm-v3.20.2-linux-amd64.tar.gz"; EXTRACT="linux-amd64/helm" ;; \
        arm64) DOWNLOAD_URL="https://get.helm.sh/helm-v3.20.2-linux-arm64.tar.gz"; EXTRACT="linux-arm64/helm" ;; \
    esac && \
    curl -fsSL --retry 3 --retry-delay 5 --retry-all-errors "${DOWNLOAD_URL}" > "${TMP_FILE}" && \
    printf "%s  %s\n" "${CHECKSUM}" "${TMP_FILE}" > "${TMP_DIR}/checksum.sha256" && \
    sha256sum -c "${TMP_DIR}/checksum.sha256" && \
    tar xzf "${TMP_FILE}" -C "${TMP_DIR}" && \
    install "${TMP_DIR}/${EXTRACT}" "/usr/local/bin/helm" && \
    rm -rf "${TMP_DIR}"

# helmv4 v4.1.4
RUN case "${ARCH}" in \
        amd64) CHECKSUM="70b2c30a19da4db264dfd68c8a3664e05093a361cefd89572ffb36f8abfa3d09" ;; \
        arm64) CHECKSUM="13d03672be289045d2ff00e4e345d61de1c6f21c1257a45955a30e8ae036d8f1" ;; \
        *) echo "Unsupported: ${ARCH}"; exit 1 ;; \
    esac && \
    export TMP_DIR=$(mktemp -d) && \
    export TMP_FILE="${TMP_DIR}/helmv4.tar.gz" && \
    case "${ARCH}" in \
        amd64) DOWNLOAD_URL="https://get.helm.sh/helm-v4.1.4-linux-amd64.tar.gz"; EXTRACT="linux-amd64/helm" ;; \
        arm64) DOWNLOAD_URL="https://get.helm.sh/helm-v4.1.4-linux-arm64.tar.gz"; EXTRACT="linux-arm64/helm" ;; \
    esac && \
    curl -fsSL --retry 3 --retry-delay 5 --retry-all-errors "${DOWNLOAD_URL}" > "${TMP_FILE}" && \
    printf "%s  %s\n" "${CHECKSUM}" "${TMP_FILE}" > "${TMP_DIR}/checksum.sha256" && \
    sha256sum -c "${TMP_DIR}/checksum.sha256" && \
    tar xzf "${TMP_FILE}" -C "${TMP_DIR}" && \
    install "${TMP_DIR}/${EXTRACT}" "/usr/local/bin/helmv4" && \
    rm -rf "${TMP_DIR}"

# slsactl v0.1.30
RUN case "${ARCH}" in \
        amd64) CHECKSUM="7ed4750766c135ddcae788d194d7ff59a57c6debdc722fd1e52c06460218f10a" ;; \
        arm64) CHECKSUM="bbbe66089135c82526677177c080f5ca4911ad1989712596338c5acdae4bb383" ;; \
        *) echo "Unsupported: ${ARCH}"; exit 1 ;; \
    esac && \
    export TMP_DIR=$(mktemp -d) && \
    export TMP_FILE="${TMP_DIR}/slsactl.tar.gz" && \
    case "${ARCH}" in \
        amd64) DOWNLOAD_URL="https://github.com/rancherlabs/slsactl/releases/download/v0.1.30/slsactl_0.1.30_linux_amd64.tar.gz"; EXTRACT="slsactl" ;; \
        arm64) DOWNLOAD_URL="https://github.com/rancherlabs/slsactl/releases/download/v0.1.30/slsactl_0.1.30_linux_arm64.tar.gz"; EXTRACT="slsactl" ;; \
    esac && \
    curl -fsSL --retry 3 --retry-delay 5 --retry-all-errors "${DOWNLOAD_URL}" > "${TMP_FILE}" && \
    printf "%s  %s\n" "${CHECKSUM}" "${TMP_FILE}" > "${TMP_DIR}/checksum.sha256" && \
    sha256sum -c "${TMP_DIR}/checksum.sha256" && \
    tar xzf "${TMP_FILE}" -C "${TMP_DIR}" && \
    install "${TMP_DIR}/${EXTRACT}" "/usr/local/bin/slsactl" && \
    rm -rf "${TMP_DIR}"

# golangci-lint v2.11.4
RUN case "${ARCH}" in \
        amd64) CHECKSUM="200c5b7503f67b59a6743ccf32133026c174e272b930ee79aa2aa6f37aca7ef1" ;; \
        arm64) CHECKSUM="3bcfa2e6f3d32b2bf5cd75eaa876447507025e0303698633f722a05331988db4" ;; \
        *) echo "Unsupported: ${ARCH}"; exit 1 ;; \
    esac && \
    export TMP_DIR=$(mktemp -d) && \
    export TMP_FILE="${TMP_DIR}/golangci-lint.tar.gz" && \
    case "${ARCH}" in \
        amd64) DOWNLOAD_URL="https://github.com/golangci/golangci-lint/releases/download/v2.11.4/golangci-lint-2.11.4-linux-amd64.tar.gz"; EXTRACT="golangci-lint-2.11.4-linux-amd64/golangci-lint" ;; \
        arm64) DOWNLOAD_URL="https://github.com/golangci/golangci-lint/releases/download/v2.11.4/golangci-lint-2.11.4-linux-arm64.tar.gz"; EXTRACT="golangci-lint-2.11.4-linux-arm64/golangci-lint" ;; \
    esac && \
    curl -fsSL --retry 3 --retry-delay 5 --retry-all-errors "${DOWNLOAD_URL}" > "${TMP_FILE}" && \
    printf "%s  %s\n" "${CHECKSUM}" "${TMP_FILE}" > "${TMP_DIR}/checksum.sha256" && \
    sha256sum -c "${TMP_DIR}/checksum.sha256" && \
    tar xzf "${TMP_FILE}" -C "${TMP_DIR}" && \
    install "${TMP_DIR}/${EXTRACT}" "/usr/local/bin/golangci-lint" && \
    rm -rf "${TMP_DIR}"

# goreleaser v2.15.2
RUN case "${ARCH}" in \
        amd64) CHECKSUM="0ebdbf0353aba566b969dde746cc4e4806f96c27aa2f3971b229a9df7611fedc" ;; \
        arm64) CHECKSUM="5db66761a98f6693161e49e1a95d28d2673a892ba60cb4a5e16736cafd41c4c9" ;; \
        *) echo "Unsupported: ${ARCH}"; exit 1 ;; \
    esac && \
    export TMP_DIR=$(mktemp -d) && \
    export TMP_FILE="${TMP_DIR}/goreleaser.tar.gz" && \
    case "${ARCH}" in \
        amd64) DOWNLOAD_URL="https://github.com/goreleaser/goreleaser/releases/download/v2.15.2/goreleaser_Linux_x86_64.tar.gz"; EXTRACT="goreleaser" ;; \
        arm64) DOWNLOAD_URL="https://github.com/goreleaser/goreleaser/releases/download/v2.15.2/goreleaser_Linux_arm64.tar.gz"; EXTRACT="goreleaser" ;; \
    esac && \
    curl -fsSL --retry 3 --retry-delay 5 --retry-all-errors "${DOWNLOAD_URL}" > "${TMP_FILE}" && \
    printf "%s  %s\n" "${CHECKSUM}" "${TMP_FILE}" > "${TMP_DIR}/checksum.sha256" && \
    sha256sum -c "${TMP_DIR}/checksum.sha256" && \
    tar xzf "${TMP_FILE}" -C "${TMP_DIR}" && \
    install "${TMP_DIR}/${EXTRACT}" "/usr/local/bin/goreleaser" && \
    rm -rf "${TMP_DIR}"

# govulncheck v1.2.0
RUN go install golang.org/x/vuln/cmd/govulncheck@a8075323febce35764797d66a61fa9e19a8d9797

# Cleanup Go caches
RUN go clean -cache -modcache

# We trust our base image and the repos that are pulled in workflows. Otherwise
# Create runner user for GitHub Actions (UID 1001)
RUN useradd -m -u 1001 -s /bin/bash runner

USER runner

ENTRYPOINT ["/bin/bash"]
