package lock

import (
	"fmt"
	"os"
	"time"

	"go.yaml.in/yaml/v4"

	"github.com/rancher/ci-image/internal/fileutil"
)

const fileHeader = "# Auto-generated by 'generate'. Do not edit manually.\n"

// Entry records the resolved state of a release-checksums tool.
type Entry struct {
	ResolvedVersion string            `yaml:"resolved_version"`
	ResolvedAt      time.Time         `yaml:"resolved_at"`
	Checksums       map[string]string `yaml:"checksums,omitempty"`
}

// Lock is the top-level structure of deps.lock.
type Lock struct {
	Tools map[string]Entry `yaml:"tools"`
}

// Read reads deps.lock at path. If the file does not exist, an empty Lock is
// returned — deps.lock is created on the first generate run.
func Read(path string) (*Lock, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Lock{Tools: map[string]Entry{}}, nil
		}
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	var l Lock
	if err := yaml.Load(data, &l); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	if l.Tools == nil {
		l.Tools = map[string]Entry{}
	}
	return &l, nil
}

// Write atomically writes l to path with a generated-file header comment.
func Write(path string, l *Lock) error {
	data, err := marshalLock(l)
	if err != nil {
		return err
	}
	return fileutil.AtomicWrite(path, data, 0o644)
}

// WriteIfChanged writes l to path only when the serialised content differs
// from the existing file. Returns true if the file was written.
func WriteIfChanged(path string, l *Lock) (bool, error) {
	data, err := marshalLock(l)
	if err != nil {
		return false, err
	}
	return fileutil.WriteIfChanged(path, data, 0o644)
}

func marshalLock(l *Lock) ([]byte, error) {
	body, err := yaml.Marshal(l)
	if err != nil {
		return nil, fmt.Errorf("marshalling lock: %w", err)
	}
	return append([]byte(fileHeader), body...), nil
}
