name: push and release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dockerfiles/**'

  workflow_dispatch:

concurrency:
  group: build-rancher-ci-image
  cancel-in-progress: false

permissions:
  contents: read
  id-token: none
  packages: write

env:
  ORG: ${{ github.repository_owner }}

jobs:
  setup:
    runs-on: ubuntu-latest
    container: registry.suse.com/bci/golang:1.26.2@sha256:0c1bfe51ea14f3e28b4730c725687331ce6aa24c61acea3b9735286789c873b9
    outputs:
      images: ${{ steps.list.outputs.images }}
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Install needed packages
        shell: bash
        run: |
          zypper -n in docker git-core make jq

      - name: Configure git
        shell: bash
        run: |
          git config --global safe.directory "$(pwd)"
          git config --global user.name "rancher-security-team[bot]"
          git config --global user.email "202797621+rancher-security-team[bot]@users.noreply.github.com"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set image version
        id: version
        shell: bash
        run: echo "value=$(date -u +%Y%m%d)-${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: Generate
        shell: bash
        run: make generate

      - name: Verify
        shell: bash
        run: make verify

      - name: List images
        id: list
        shell: bash
        run: |
          images=$(awk '/^images:/{f=1;next} /^[a-zA-Z]/{f=0} f && /- /{print $2}' images-lock.yaml | jq -Rcs '[split("\n")[] | select(. != "")]')
          echo "images=$images" >> "$GITHUB_OUTPUT"

  build-ci-image:
    needs: [setup]
    runs-on: ubuntu-latest
    container: registry.suse.com/bci/golang:1.26.2@sha256:0c1bfe51ea14f3e28b4730c725687331ce6aa24c61acea3b9735286789c873b9
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.setup.outputs.images) }}
    steps:
      - name: Install needed packages
        shell: bash
        run: |
          zypper -n in docker git-core make

      - name: Configure git
        shell: bash
        run: |
          git config --global safe.directory "$(pwd)"
          git config --global user.name "rancher-security-team[bot]"
          git config --global user.email "202797621+rancher-security-team[bot]@users.noreply.github.com"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Log in to GHCR
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io

      - name: Build and push image
        shell: bash
        run: make push NO_CACHE=1 ORG="${ORG}" IMAGE="${{ matrix.image }}" VERSION="${{ needs.setup.outputs.version }}"
